PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS migrations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  run_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bosses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  week INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  boss_id INTEGER NOT NULL,
  type TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  answer_key TEXT NOT NULL,
  cefr TEXT DEFAULT 'A2',
  FOREIGN KEY (boss_id) REFERENCES bosses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  boss_id INTEGER NOT NULL,
  seed INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  finished_at INTEGER,
  hp INTEGER NOT NULL,
  score INTEGER NOT NULL,
  combo INTEGER NOT NULL,
  current_index INTEGER NOT NULL,
  total INTEGER NOT NULL,
  correct INTEGER NOT NULL,
  FOREIGN KEY (boss_id) REFERENCES bosses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  task_id INTEGER NOT NULL,
  selected TEXT,
  is_correct INTEGER NOT NULL,
  at_ms INTEGER NOT NULL,
  task_snapshot TEXT,
  FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);
